#!/bin/bash

set -Eeu -o pipefail

AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-eu-central-1}"
AWS_REGION="${AWS_DEFAULT_REGION}"
export AWS_PROFILE AWS_DEFAULT_REGION AWS_REGION

_terraform() {
  (
    cd terraform/ || true

    terraform init
    terraform "$@"
  )
}

usage() {
    echo "Usage: $0 terraform [plan|apply]"
}

CMD=${1:-}
shift || true
case ${CMD} in
  terraform) _terraform "$@" ;;
  *) usage ;;
esac
